name: Build and deploy phar
on:
  - push

jobs:
  phar:
    name: Build phar

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: json, mbstring, intl, apcu
          tools: composer, phive
          ini-values: assert.exception=1, zend.assertions=1, apc.enabled=1, apc.enable_cli=1

      - name: Install highest dependencies with composer
        env:
          COMMERCETOOLS_CLIENT_ID: ${{ secrets.COMMERCETOOLS_CLIENT_ID }}
          COMMERCETOOLS_CLIENT_SECRET: ${{ secrets.COMMERCETOOLS_CLIENT_SECRET }}
          COMMERCETOOLS_PROJECT: ${{ secrets.COMMERCETOOLS_PROJECT }}
        run: composer install --no-ansi --no-interaction --no-progress --no-suggest --no-dev

      - name: Install box
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: phive install humbug/box --force-accept-unsigned

      - name: Compile phar
        run: tools/box compile

      - uses: actions/upload-artifact@v1
        with:
          name: commercetools-php-sdk-${{ github.run_number }}.phar
          path: commercetools-php-sdk.phar
